name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/pixel-frontend/
            rm -r Pixel8Labs-test
            git clone https://github.com/williamrusdyputra/Pixel8Labs-test.git
            cd Pixel8Labs-test/frontend/
            npm install
            npm run build
            pm2 delete pixel-frontend
            pm2 start npm --name "pixel-frontend" -- start
